language: go

addons:
  apt:
    packages:
    # needed only if you use the snap pipe:
    - snapcraft
services:
- docker
script:
- make travisbuild
env:
  global:
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor
    - secure: vlmqgSaI4YF4XxXVtbHb8/5KP7DL9dB516dnpEBXHPmI03PsQ4nSgOFw3YxhYKA/EaP9SZ8Pl3CTYKiE8pwsRQ8MqREM6YK45zX5tgbNVsnr/2ASLFVZvsCCbBOfiDrZkSg3zXeAszgQN/Zo5gelxo0cdUCTaAz0ZH+I3VyTzQKDRmBahHSmjnAZFjHCYoMR9tt8jRMDdtY8Gt098ciuTbrxSMVMIVPkNZX/Cy54FZoU4Ua5sWFIBviBeisH3Qg4xYflHjX0BXPuvu+eLTHVLXenE+mi13dxBb5+3GKcOR/t64L98sJLsOBIRK34q1A35lN2XB1JZZ3iDVkAlIwlF6nO+dJZQhU11QDe7kjqbIkZYEa8Fw7OOG5UxsGSJfofSky0Wnu15HZnGh/34rWFjojId6YPmvblAX3zWcLdNcPPKuuhymkmvHrjMqEtcMC0WHbuQEoBRH8brDvG4IEhIWmrt6iCElCT2TdOJCH8W/kVGAQKlWICf5oi+oY3po/MRk9LXycqc0zt+kSVBXLA7IwHVXNuZKwVrJmpwe9Osbq3iN3E+1YnI24+su0pzDG+10i2VKivVpv/rqxJ0MKwn7Iu2XB42qSF11+MaIrEpz41j07Ymz92Eqr4ME1N4gLyykICnFIrXSNr30KiHLpgqcuG0Q8JTkn/J/RYeWxQgvg=
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux