language: go
go:
- 1.10.x
services:
- docker
install:
- go get github.com/kardianos/govendor
script:
- make travisbuild
after_success:
- make release
env:
  global:
    secure: vlmqgSaI4YF4XxXVtbHb8/5KP7DL9dB516dnpEBXHPmI03PsQ4nSgOFw3YxhYKA/EaP9SZ8Pl3CTYKiE8pwsRQ8MqREM6YK45zX5tgbNVsnr/2ASLFVZvsCCbBOfiDrZkSg3zXeAszgQN/Zo5gelxo0cdUCTaAz0ZH+I3VyTzQKDRmBahHSmjnAZFjHCYoMR9tt8jRMDdtY8Gt098ciuTbrxSMVMIVPkNZX/Cy54FZoU4Ua5sWFIBviBeisH3Qg4xYflHjX0BXPuvu+eLTHVLXenE+mi13dxBb5+3GKcOR/t64L98sJLsOBIRK34q1A35lN2XB1JZZ3iDVkAlIwlF6nO+dJZQhU11QDe7kjqbIkZYEa8Fw7OOG5UxsGSJfofSky0Wnu15HZnGh/34rWFjojId6YPmvblAX3zWcLdNcPPKuuhymkmvHrjMqEtcMC0WHbuQEoBRH8brDvG4IEhIWmrt6iCElCT2TdOJCH8W/kVGAQKlWICf5oi+oY3po/MRk9LXycqc0zt+kSVBXLA7IwHVXNuZKwVrJmpwe9Osbq3iN3E+1YnI24+su0pzDG+10i2VKivVpv/rqxJ0MKwn7Iu2XB42qSF11+MaIrEpz41j07Ymz92Eqr4ME1N4gLyykICnFIrXSNr30KiHLpgqcuG0Q8JTkn/J/RYeWxQgvg=
